import "./globals.css";
import ThemeProviderWrapper from "./theme/ThemeProviderWrapper";
import '@fontsource/roboto/400.css';
import '@fontsource/roboto/500.css';
import '@fontsource/roboto/700.css';



export const metadata = {
  title: "Admin Panel",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html>
      <body lang="en">
          {children}
      </body>
    </html>
  );
}